# Generated by Django 5.0.6 on 2024-06-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_career_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cv',
            field=models.FileField(upload_to='../Amar Project/media/cvs/'),
        ),
    ]
