# Generated by Django 5.0.6 on 2024-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_career_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cv',
            field=models.FileField(upload_to='C:/TOPS/Django/Amar Project/media/cvs/'),
        ),
    ]
