# Generated by Django 5.0.6 on 2024-06-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_career_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='phone',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='10', max_length=10),
        ),
    ]
